name: event_planning
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any


  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.4
  cloud_firestore: ^5.6.11
  firebase_core: ^3.15.1
  firebase_auth: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  generate: true


  uses-material-design: true
  assets:
    - assets/images/


