// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBliPhCyK3gRCJ5LjCsHfaHwgUpGIdcsTU',
    appId: '1:653815217456:android:2be2c0ae42269c2afedcf5',
    messagingSenderId: '653815217456',
    projectId: 'device-streaming-04615bf8',
    storageBucket: 'device-streaming-04615bf8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmjy3X6af_D-7_438eIDPDO2mD1IiGz2Y',
    appId: '1:653815217456:ios:e345fc713a8e81e1fedcf5',
    messagingSenderId: '653815217456',
    projectId: 'device-streaming-04615bf8',
    storageBucket: 'device-streaming-04615bf8.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmjy3X6af_D-7_438eIDPDO2mD1IiGz2Y',
    appId: '1:653815217456:ios:e345fc713a8e81e1fedcf5',
    messagingSenderId: '653815217456',
    projectId: 'device-streaming-04615bf8',
    storageBucket: 'device-streaming-04615bf8.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7X1iEIlARD7IdhMQbjI3jheLs3v0LPUY',
    appId: '1:653815217456:web:2c29bd7bb1439a99fedcf5',
    messagingSenderId: '653815217456',
    projectId: 'device-streaming-04615bf8',
    authDomain: 'device-streaming-04615bf8.firebaseapp.com',
    storageBucket: 'device-streaming-04615bf8.firebasestorage.app',
  );
}
